### ISSUE TITLE
linear_alg-mid-100x100-sp and loops-all-mid-10k-sp compilation fails

### ISSUE THREAD

**Issue by TianyangL** [eembc/coremark-pro#1]
I use "make TARGET=linux64 build".  
The following error occurs:

/usr/bin/gcc -c -g -O2 -DNDEBUG -DHOST_EXAMPLE_CODE=1 -std=gnu99   -DHAVE_SYS_STAT_H=1 -DUSE_NATIVE_PTHREAD=1 -DGCC_INLINE_MACRO=1 -DNO_RESTRICT_QUALIFIER=1 -DEE_SIZEOF_LONG=8 -DEE_SIZEOF_PTR=8 -DEE_PTR_ALIGN=8 -DHAVE_SYS_STAT_H=1 -DUSE_NATIVE_PTHREAD=1 -DGCC_INLINE_MACRO=1 -DNO_RESTRICT_QUALIFIER=1 -DEE_SIZEOF_LONG=8 -DEE_SIZEOF_PTR=8 -DEE_PTR_ALIGN=8 -DEE_SIZEOF_INT=4 -DEE_SIZEOF_LONG=8  -Wall -Wno-long-long -fno-asm -fsigned-char     -DUSE_FP32 -I/home/tyliu/project/coremark-pro/mith/include -I/home/tyliu/project/coremark-pro/mith/al/include -I/home/tyliu/project/coremark-pro/mith/al/include /home/tyliu/project/coremark-pro/workloads/linear_alg-mid-100x100-sp/linear_alg-mid-100x100-sp.c -o linear_alg-mid-100x100-sp.o
cd /home/tyliu/project/coremark-pro/builds/linux64/gcc64/obj/bench/fp/linpack/SP && make -f /home/tyliu/project/coremark-pro/benchmarks/fp/linpack/SP/../Makefile build
make[3]: Entering directory '/home/tyliu/project/coremark-pro/builds/linux64/gcc64/obj/bench/fp/linpack/SP'
make[3]: /home/tyliu/project/coremark-pro/benchmarks/fp/linpack/SP/../Makefile: No such file or directory
make[3]: *** No rule to make target '/home/tyliu/project/coremark-pro/benchmarks/fp/linpack/SP/../Makefile'.  Stop.
make[3]: Leaving directory '/home/tyliu/project/coremark-pro/builds/linux64/gcc64/obj/bench/fp/linpack/SP'
/home/tyliu/project/coremark-pro/workloads/linear_alg-mid-100x100-sp//Makefile:71: recipe for target '/home/tyliu/project/coremark-pro/builds/linux64/gcc64/obj/bench/fp/linpack/SP/done.build' failed
make[2]: *** [/home/tyliu/project/coremark-pro/builds/linux64/gcc64/obj/bench/fp/linpack/SP/done.build] Error 2
make[2]: Leaving directory '/home/tyliu/project/coremark-pro/builds/linux64/gcc64/obj/workloads/linear_alg-mid-100x100-sp'

**Comment by petertorelli** [comment]
During the SVN->GIT port, the 5 empty "SP" folders were left out. Pushed in edeac7e2e11e601d91728e346c19abe3b68f1cbf. Please do a pull and try to build again.

**Comment by TianyangL** [comment]
Thank you
