### ISSUE TITLE
Compiling without Make

### ISSUE THREAD

**Issue by muke101** [eembc/coremark-pro#11]
I'm doing some research related to LLVM and need the LLVM IR of each individual benchmark. This means I have to bypass the Makefile and use clang manually to generate IR from the relevant C files. I've managed to do this but when I then compile the IR to binary and run the benchmark workload, the workload prints that there's been an error. If I compile with make then the benchmarks all run fine.

For example, for the loop kernels benchmark, in the directory `coremark-pro/workloads/loops-all-mid-10k-sp`, I run the following:
`clang -O3 -S -emit-llvm -I ../../mirth/include -I ../../mirth/al/include -I ../../benchmarks/fp/loops -o loops-all-mid-10k-sp.ll`

I also defined `USE_FP32=1`.

I run the same clang command for all the .c files in `/mirth/src`, `/mirth/al/src` and `/benchmarks/fp/loops` before combining all the `.ll` files into one using `llvm-link`. I then compile the single IR file to a binary and execute, and get the following:

```
$ ./a.out -v0
-  Info: Starting Run...
-- Workload:loops-all-mid-10k-sp=1814569103
-- loops-all-mid-10k-sp:time(ns)=7000
-- loops-all-mid-10k-sp:ERRORS=50
-- loops-all-mid-10k-sp:contexts=1
-- loops-all-mid-10k-sp:iterations=50
-- loops-all-mid-10k-sp:time(secs)=       7
-- loops-all-mid-10k-sp:secs/workload=    0.14
-- loops-all-mid-10k-sp:workloads/sec= 7.14286
-- accbits:min=0
-- accbits:max=0
-- accbits:avg=0
-- Done:loops-all-mid-10k-sp=1814569103
```

What am I missing in my build process to make this work? I've tried going through coremark's own make files but can't figure it out. Any help would be appreciated, thanks.

**Comment by petertorelli** [comment]
It looks like you've succeeded in porting it. I'm pretty sure you are encountering errors regarding floating point accuracy since the `loops` test is a very accuracy sensitive test, and some compiler options can impact this. Try enabling `BMDEBUG` and `DEBUG_ACCURATE_BITS`. This will print out the values that failed the bit-accuracy test. You may need to experiment with the clang floating-point options.

**Comment by muke101** [comment]
I've tried to look into this and it seems like you're right, but I can't find how to fix the problem. Although for my purposes I don't actually need the results to be correct, I just need to run the program - are you able to comment at all on how if at all the floating point accuracy might effect the behavior of the program?

**Comment by petertorelli** [comment]
You can alter `MIN_ACC_BITS_FP32` and `MIN_ACC_BITS_FP64` to reduce the number of bits compared. Here is an example of how it is used in `th_bignum.c`:

```C
void acc_summary_info(intparts *sig, intparts *ref, e_u32 accbits) {
	svals(&acc_summary.sig_exp,sig->exp);
	svals(&acc_summary.ref_exp,ref->exp);
	svals(&acc_summary.bits,accbits);
	if (accbits<MIN_ACC_BITS_FP)
		acc_summary.counts[accbits]++;
	else
		acc_summary.counts[MAX_ACC_COUNTS]++;
}
```
