### ISSUE TITLE
How to run workloads in bare-metal with multicore?

### ISSUE THREAD

**Issue by ksbaaa** [eembc/coremark-pro#13]
Hi,
    I have seen the video tutorial of CoreMark-PRO in YouTube, and I know how to transplant one workload to the bare-metal. But I don’t understand how to transplant nine workload to a bare-metal, did I need to download and run the workload one by one? Run 9 times with respective workload?
    If so, what should I do to allocate one workload to multicore? Such as Stm32H747, which has two cores, Cortex-M4 and M7, how can I make two cores work simultaneously to calculate the workload? If I can only use one core each time, it’s obvious that I don’t fully use the resources.

**Comment by petertorelli** [comment]
> did I need to download and run the workload one by one? Run 9 times with respective workload?

Yes.

> If so, what should I do to allocate one workload to multicore? 

You will need to use a POSIX pthread compliant library to schedule. If you look at `mith_main()`, you can see how the workloads are dispatched:

```c
	/* now to start the timer, and get the first item */
	/* from here on we need to worry about thread safety */
	al_signal_start();
	/* create the thread pool */
	for (i=0; i<num_contexts; i++)
		al_thread_create(&(context[i].thread),bench_thread,(void *)(&context[i]));
	/* and wait until threads are all done executing */
	for (i=0; i<num_contexts; i++)
		al_thread_join((context[i].thread),&context_ret);
	total_time=al_signal_finished();
	/* workload is now done, report results */
	/* from here on, only one thread operates */
```

The `al_*` functions constitute the "Abstraction Layer". This layer needs to be customized if using multi-core in a non-POSIX-pthread way. If you look at the default SMP implementation, `mith/al/src/al_smp.c`, notice it defaults to `pthreads`. If that is not supported, you need to use the STM strategy for scheduling threads on asymmetric cores. I don't recall what they use (AMP), but you need to implement this yourself.

**Comment by petertorelli** [comment]
Closing this since there has been no follow up.
