### ISSUE TITLE
Can I ask where does the number '1000' come from? Thanks!

### ISSUE THREAD

**Issue by h2th3k** [eembc/coremark-pro#15]
https://github.com/eembc/coremark-pro/blob/4832cc67b0926c7a80a4b7ce0ce00f4640ea6bec/README.md?plain=1#L132

**Comment by petertorelli** [comment]
Because 1000 iterations is effectively 0.1% tolerance of the minimum timer resolution.

**Comment by h2th3k** [comment]
"minimum timer resolution" you mean the tick on the system? e.g. 100 on some unix systems

**Comment by petertorelli** [comment]
Whatever you choose it to be. Real time clock, dedicated hardware timer, OS timer. CoreMark runs on almost any platform.
