### ISSUE TITLE
GLIBC_2.27' not found required by arm-linux-gnueabihf

### ISSUE THREAD

**Issue by sunildogra1710** [eembc/coremark-pro#17]
As you suggest "if you had used arm-linux-eabi then it would have compiled. This is unrelated to the benchmark. Here [is a good explanation](https://wiki-archive.linaro.org/WorkingGroups/ToolChain/FAQ#What_is_the_differences_between_.2BIBw-arm-none-eabi-.2BIB0_and_.2BIBw-arm-linux-gnueabihf.2BIB0.3F_Can_I_use_.2BIBw-arm-linux-gnueabihf.2BIB0_tool_chain_in_bare-metal_environment.3F_How_do_you_know_which_toolchain_binary_to_use_where.3F) of the three components in the toolchain name."

I have downloaded GNU tool chain version 11.3  “https://snapshots.linaro.org/gnu-toolchain/  but getting the below error.
./linaro/gcc-linaro-11.3.1-2022.06-x86_64_arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/11.3.1/../../../../arm-linux-gnueabihf/bin/ld: /lib64/libc.so.6: version `GLIBC_2.27' not found (required by ./linaro/gcc-linaro-11.3.1-2022.06-x86_64_arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/11.3.1/../../../../arm-linux-gnueabihf/bin/ld)
 
I have downloaded “sysroot-glibc-linaro-2.34-2022.06-arm-linux-gnueabihf” from the gnu-tool chain package and changed the path but still getting GLIB_2.27 not found error. 

please help me on this.

**Comment by petertorelli** [comment]
This means the executable requires the GLIB_2.27 libraries. This happens when you run an application on an OS that is not up-to-date. You need to update libc on your machine. This is unrelated to CoreMark-Pro. Please try StackExchange / Google / Etc.
