### ISSUE TITLE
Incorrect Coremark-Pro score calculation

### ISSUE THREAD

**Issue by ateymourian** [eembc/coremark-pro#2]
According to the documentation the coremark pro score should be calculated with:

100 x geomean( ( subtestscore / reference score ) * scale factor)

but it's in fact the produced score seems to be:

1000 x geomean( ( subtestscore / reference score ) * scale factor)

The produced score seems to be 10x what it should be

**Comment by petertorelli** [comment]
You are correct. The weights are listed in the `cert_mark.pl` script [here](https://github.com/eembc/coremark-pro/blob/d15927b014de025b618b927d0d796088c3183378/util/perl/cert_mark.pl#L38-L53 ). Incoming documentation fix.
