### ISSUE TITLE
Unable to build the benchmark for ARM AARCH64

### ISSUE THREAD

**Issue by m-abaas** [eembc/coremark-pro#6]
Hello, 

I'm trying to cross compile the benchmark for ARM AARCH64 .. I'm using: **gcc-7.3**

I basically changed the following about **util/make/gcc64.mk**:
CC      = $(COMPILER_HOME)/bin/aarch64-buildroot-linux-gnu-gcc
AS      = $(COMPILER_HOME)/bin/aarch64-buildroot-linux-gnu-as
LD      = $(COMPILER_HOME)/bin/aarch64-buildroot-linux-gnu-ld
AR      = $(COMPILER_HOME)/bin/aarch64-buildroot-linux-gnu-ar

Also: 
INCLUDE =  $(COMPILER_HOME)/include/

However, the following error occurs when I use `make TARGET=linux64 build`:

`coremark-pro/coremark-pro/builds/linux64/gcc64/obj/mith.a(th_lib.o): undefined reference to symbol 'vsnprintf@@GLIBC_2.17'
/project/codelink/tools/toolchains/mentor/aarch64/gcc-7.3.0/bin/../aarch64-buildroot-linux-gnu/sysroot/lib64/libc.so.6: error adding symbols: DSO missing from command line
`

Any idea how to resolve this? 
Thank you in advance.

**Comment by petertorelli** [comment]
It looks like your compiler is not the same version as the lib files on your system. Try updating glibc. This isn't a CoreMark-PRO issue.

**Comment by m-abaas** [comment]
Thanks a lot @petertorelli ! 

Actually, the issue turned out to be in linking. 
The gcc64.mak is using **gcc** not **ld** for linking: 

LD = $(TOOLS)/bin/gcc

Unfortunately, I didn't notice it till now.

**Comment by petertorelli** [comment]
@m-abaas,
Thanks for the follow up. If I understand you correctly, `LD` was being re-defined _after_ you had set it to the Arm `ld`?

**Comment by m-abaas** [comment]
@petertorelli 
Thank you for the follow up as well. 
LD was not re-defined after setting it to ```ARM ld```. The error message came from ```ARM ld``` itself.  
What happened is that I didn't really notice LD was being originally set to ```gcc```, so I set it to ```ARM ld``` and **I didn't change any of the arguments passed to linker**. 

Just to confirm, I've just re-run the experiment to double check, and the benchmark compiles successfully when: 
```LD      =  $(COMPILER_HOME)/bin/aarch64-buildroot-linux-gnu-gcc```
But issues an error when: 
```LD      =  $(COMPILER_HOME)/bin/aarch64-buildroot-linux-gnu-ld```
