### ISSUE TITLE
Query : WORKLOAD RESULTS

### ISSUE THREAD

**Issue by pankajjoshi347** [eembc/coremark-pro#8]
Hi,
I am running Coremark-pro on ARM by running individual binary and i believe you are using following 

**1000 x geomean( ( subtestscore / reference score ) * scale factor)**

but i am not able to understand how you are calculating **subtestscore and reference score**

I am attaching **output for cjpeg-rose7-preset.exe**  

pankaj@pankaj~# ./cjpeg-rose7-preset.exe                                                              
Rose256.bmp data supplied by C array                                                                         
>> Data Set                 : Rose256.bmp                                                                    
>> Output File              : Rose256.jpg                                                                    
Rose256.bmp data supplied by C array                                                                         
>> Data Set                 : Rose256.bmp                                                                    
>> Output File              : Rose256.jpg                                                                    
Rose256.bmp data supplied by C array                                                                         
>> Data Set                 : Rose256.bmp                                                                    
>> Output File              : Rose256.jpg                                                                    
Rose256.bmp data supplied by C array                                                                         
>> Data Set                 : Rose256.bmp                                                                    
>> Output File              : Rose256.jpg                                                                    
Rose256.bmp data supplied by C array                                                                         
>> Data Set                 : Rose256.bmp                                                                    
>> Output File              : Rose256.jpg                                                                    
Rose256.bmp data supplied by C array                                                                         
>> Data Set                 : Rose256.bmp                                                                    
>> Output File              : Rose256.jpg                                                                    
Rose256.bmp data supplied by C array                                                                         
>> Data Set                 : Rose256.bmp                                                                    
>> Output File              : Rose256.jpg                                                                    
-  Info: Starting Run...                                                                                     
-- Workload:cjpeg-rose7-preset=236760500                                                                     
-- cjpeg-rose7-preset:time(ns)=2009                                                                          
-- cjpeg-rose7-preset:contexts=1                                                                             
-- cjpeg-rose7-preset:iterations=1                                                                           
-- cjpeg-rose7-preset:time(secs)=   2.009                                                                    
-- cjpeg-rose7-preset:secs/workload=   2.009                                                                 
-- cjpeg-rose7-preset:workloads/sec= 0.49776                                                                 
Info: This run was executed with verification turned on! For performance results, use -v0.                   
-- cjpeg-data1:UID=10000                                                                                     
-- cjpeg-data1:fails=0                                                                                       
-- cjpeg-data1:time(ticks)=269                                                                               
-- cjpeg-data1:count=1                                                                                       
-- cjpeg-data1:repeats=1                                                                                     
-- cjpeg-data1:v1=0                                                                                          
-- cjpeg-data1:v2=0
-- cjpeg-data1:v3=0                                                                                          
-- cjpeg-data1:v4=0
-- cjpeg-data1:f1=0.000000e+00
-- cjpeg-data1:f2=0.000000e+00
-- cjpeg-data1:f3=0.000000e+00
-- cjpeg-data1:f4=0.000000e+00
-- cjpeg-data1:secs/repeat=   0.269
-- cjpeg-data1:repeats/sec= 3.71747
-- cjpeg-data1:time(secs)=   0.269
-- cjpeg-data1:secs/item=   0.269
-- cjpeg-data1:items/sec= 3.71747
-- cjpeg-data1:UID=10001
-- cjpeg-data1:fails=0
-- cjpeg-data1:time(ticks)=262
-- cjpeg-data1:count=1
-- cjpeg-data1:repeats=1
-- cjpeg-data1:v1=0
-- cjpeg-data1:v2=0
-- cjpeg-data1:v3=0
-- cjpeg-data1:v4=0
-- cjpeg-data1:f1=0.000000e+00
-- cjpeg-data1:f2=0.000000e+00
-- cjpeg-data1:f3=0.000000e+00
-- cjpeg-data1:f4=0.000000e+00
-- cjpeg-data1:secs/repeat=   0.262
-- cjpeg-data1:repeats/sec= 3.81679
-- cjpeg-data1:time(secs)=   0.262
-- cjpeg-data1:secs/item=   0.262
-- cjpeg-data1:items/sec= 3.81679
-- cjpeg-data1:UID=10002
-- cjpeg-data1:fails=0
-- cjpeg-data1:time(ticks)=264
-- cjpeg-data1:count=1
-- cjpeg-data1:repeats=1
-- cjpeg-data1:v1=0
-- cjpeg-data1:v2=0
-- cjpeg-data1:v3=0
-- cjpeg-data1:v4=0
-- cjpeg-data1:f1=0.000000e+00
-- cjpeg-data1:f2=0.000000e+00
-- cjpeg-data1:f3=0.000000e+00
-- cjpeg-data1:f4=0.000000e+00
-- cjpeg-data1:secs/repeat=   0.264
-- cjpeg-data1:repeats/sec= 3.78788
-- cjpeg-data1:time(secs)=   0.264
-- cjpeg-data1:secs/item=   0.264
-- cjpeg-data1:items/sec= 3.78788
-- cjpeg-data1:UID=10003
-- cjpeg-data1:fails=0
-- cjpeg-data1:time(ticks)=265
-- cjpeg-data1:count=1
-- cjpeg-data1:repeats=1
-- cjpeg-data1:v1=0
-- cjpeg-data1:v2=0
-- cjpeg-data1:v3=0
-- cjpeg-data1:v4=0
-- cjpeg-data1:f1=0.000000e+00
-- cjpeg-data1:f2=0.000000e+00
-- cjpeg-data1:f3=0.000000e+00
-- cjpeg-data1:f4=0.000000e+00
-- cjpeg-data1:secs/repeat=   0.265
-- cjpeg-data1:repeats/sec= 3.77358
-- cjpeg-data1:time(secs)=   0.265
-- cjpeg-data1:secs/item=   0.265
-- cjpeg-data1:items/sec= 3.77358
-- cjpeg-data1:UID=10004
-- cjpeg-data1:fails=0
-- cjpeg-data1:time(ticks)=249
-- cjpeg-data1:count=1
-- cjpeg-data1:repeats=1
-- cjpeg-data1:v1=0
-- cjpeg-data1:v2=0
-- cjpeg-data1:v3=0
-- cjpeg-data1:v4=0
-- cjpeg-data1:f1=0.000000e+00
-- cjpeg-data1:f2=0.000000e+00
-- cjpeg-data1:f3=0.000000e+00
-- cjpeg-data1:f4=0.000000e+00
-- cjpeg-data1:secs/repeat=   0.249
-- cjpeg-data1:repeats/sec= 4.01606
-- cjpeg-data1:time(secs)=   0.249
-- cjpeg-data1:secs/item=   0.249
-- cjpeg-data1:items/sec= 4.01606
-- cjpeg-data1:UID=10005
-- cjpeg-data1:fails=0
-- cjpeg-data1:time(ticks)=250
-- cjpeg-data1:count=1
-- cjpeg-data1:repeats=1
-- cjpeg-data1:v1=0
-- cjpeg-data1:v2=0
-- cjpeg-data1:v3=0
-- cjpeg-data1:v4=0
-- cjpeg-data1:f1=0.000000e+00
-- cjpeg-data1:f2=0.000000e+00
-- cjpeg-data1:f3=0.000000e+00
-- cjpeg-data1:f4=0.000000e+00
-- cjpeg-data1:secs/repeat=    0.25
-- cjpeg-data1:repeats/sec=       4
-- cjpeg-data1:time(secs)=    0.25
-- cjpeg-data1:secs/item=    0.25
-- cjpeg-data1:items/sec=       4
-- cjpeg-data1:UID=10006
-- cjpeg-data1:fails=0
-- cjpeg-data1:time(ticks)=259
-- cjpeg-data1:count=1
-- cjpeg-data1:repeats=1
-- cjpeg-data1:v1=0
-- cjpeg-data1:v2=0
-- cjpeg-data1:v3=0
-- cjpeg-data1:v4=0
-- cjpeg-data1:f1=0.000000e+00
-- cjpeg-data1:f2=0.000000e+00
-- cjpeg-data1:f3=0.000000e+00
-- cjpeg-data1:f4=0.000000e+00
-- cjpeg-data1:secs/repeat=   0.259
-- cjpeg-data1:repeats/sec=   3.861
-- cjpeg-data1:time(secs)=   0.259
-- cjpeg-data1:secs/item=   0.259
-- cjpeg-data1:items/sec=   3.861
-- Items:total(ticks)=1818
-- Items:total(secs)=   1.818
-- Done:cjpeg-rose7-preset=236760500

    
Can you please help me from above result how we can get subtestscore and reference score and also following ???
1) MultiCore  (iter/s)
2) SingleCore   (iter/s)
3)  Scaling

Thanks

**Comment by petertorelli** [comment]
If you look at the make flow, you will see that it calls a PERL script to compute the scores from the log files.

Please refer to [these lines of code](https://github.com/eembc/coremark-pro/blob/d5b4f2ba7ba31e37a5aa93423831e7d5eb933868/util/perl/cert_mark.pl#L40-L53):

~~~
	'CoreMark-PRO' => {
		'factor' => 1000,
		'geomean' => {
			'cjpeg-rose7-preset' => (1 / 40.3438),
			'linear_alg-mid-100x100-sp' => (1 / 38.5624),
			'loops-all-mid-10k-sp' => (1 / 0.87959),
			'nnet_test' => (1 / 1.45853 ),
			'parser-125k' => (1 / 4.81116),
			'radix2-big-64k' => (1 / 99.6587),
			'sha-test' => (1 / 48.5201),
			'zip-test' => (1 / 21.3618),
			'core' => (10000 / 2855)
		}
	},
~~~

These reference scores were selected from an internal platform when the benchmark was written.

All scores, single and multi are computed by this script. The scaling is simply the ratio of the two scores.

Does this answer your question?

**Comment by pankajjoshi347** [comment]
I have attached log reports for cjpeg-rose7-preset.exe can you show me how we can calculate it,i understood for geomean and factor you are going fo follow pearl script.i want to understand the complete calculation for one binary because due to some issue i am simply running binaries on my target so not able to run pearl script.
Thanks

**Comment by petertorelli** [comment]
The result is the geomean of each score times the weights I provided above.
